#! /usr/bin/python3

import mlabgen
from sys import argv
from os import chdir, listdir
from os.path import join
from string import Template

if ("-h" in argv) or (len(argv) < 4):
    print("usage: mlabgen-dir-html [HTML] [DIRINFO] [OUT] [DIR]")
    exit()


index = open(argv[1], "r").read()
beg = index.find("$$") + 2
index_line = index[beg:beg + index[beg:].rfind("$$")]
table = ""

modules = {}

ls = listdir(argv[4])
ls.sort()
for module in ls:
    try:
        if "PrjInfo.txt" in listdir(join(argv[4], module)):
            prjinfo = mlabgen.prjinfo2dict(join(argv[4], module, "PrjInfo.txt"))
            if prjinfo["Dev"] == "False":
                prjinfo["Module"] = module
                modules[module[:-3]] = prjinfo
        elif "DirInfo.txt" in listdir(join(argv[4], module)):
            prjinfo = mlabgen.prjinfo2dict(join(argv[4], module, "DirInfo.txt"))
            if prjinfo["Dev"] == "False":
                prjinfo["Module"] = module
                modules[module] = prjinfo
    except NotADirectoryError:
        pass

for module in modules:
    table += Template(index_line).safe_substitute(modules[module])


open(argv[3], "w").write(Template(index.replace(index_line, table).replace("$$", "")).safe_substitute(mlabgen.prjinfo2dict(argv[2])))
