#! /usr/bin/python3

import mlabgen
from sys import argv

descr = mlabgen.dict_str_rm("\n", mlabgen.descr2dict(open(argv[1], "r").readlines()))

try:
    md = open(argv[2], "r+")
except FileNotFoundError:
    md = open(argv[2], "w")

mdlines = md.readlines()
md.seek(0)

for line in mdlines:
    if ("Author: " == line[0:8]) or ("Dimensions: " == line[0:12]):
        mdlines.remove(str(line))


mdlines.append("Author: {}\n".format(descr["Comment3"]))
mdlines.append("Dimensions: {}\n".format(input("Dimensions: ")))
md.writelines(mdlines)
md.close()
