#! /usr/bin/python3

import mlabgen
from sys import argv

if ("-h" in argv) or (len(argv) < 2):
    print("usage: mlabgen-module-prjinfo [-h] [PRJINFO] [SCH] [OUT]")
    exit()

descr = mlabgen.dict_str_rm("\n", mlabgen.descr2dict(open(argv[2], "r").readlines()))

prjinfo = mlabgen.prjinfo2dict(argv[1])
prjinfo.update({"Author" : descr["Comment3"][1:-1],
                "Descr" : descr["Comment2"][1:-1].replace("\\\\n", "\n")})

open(argv[3], "w").write(mlabgen.dict2prjinfo(prjinfo))
